### ISSUE TITLE
Translation function is broken

### ISSUE THREAD

**Issue by agu3010** [kit-ipe/WAVE-Client-Renderer#30]
Volume not translating on right click drag. It used to be possible before

**Comment by nicolaisi** [comment]
It is not "broken". It is disabled. 7335c6fad4a1d218cfd1c5bee2f63a6ea58505a6
do we even need it? I think we don't. If you think we need it, I can open one task for you to make this a useful feature.

**Comment by agu3010** [comment]
Matthias specifically asked for it. What is the task? I'd like to know more. Thanks for the quick response

**Comment by nicolaisi** [comment]
Matthias specifically asked for it doesn't justify why we need it. Anyway, I hope you already fixed the double loading issue (urgent issue).

I will close this since this is off-topic.

**Comment by agu3010** [comment]
ok, leaving it to your best judgement
