### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by matze** [kit-ipe/WAVE-Client-Renderer#33]
Can't find anything quickly but I'd be interested in API calls and options to the renderer constructor. It's a pity, I had to find out how to enable the ISO surface rendering by reading the report ;-)

**Comment by nicolaisi** [comment]
Sorry, there is no documentation available. There's always a lot of change but recently everything starts to stay as it is, i.e., we have a decent shader implementation. Also, I'm not sure how I should structure the API calls. Till now, the API calls are defined on the fly (I don't really like them).

We can discuss this and maybe you can advise me on the API namings.

**Comment by matze** [comment]
> We can discuss this and maybe you can advise me on the API namings.

I'm okay with the naming, I just don't know what's available without grepping through the code. If it's not a lot you can also just mention them and their purpose in the README.

**Comment by nicolaisi** [comment]
For NOVA, there's not much, I'll update the README later.
