### ISSUE TITLE
Partial data is wrongly located

### ISSUE THREAD

**Issue by matze** [kit-ipe/WAVE-Client-Renderer#34]
I always wondered why I saw some weird artifacts on the surrounding box. Turns out it's data from the opposite side of the cube. Here's an example, the full (but slightly cut) volume on the left and the volume sliced towards one side on the right. Circled in red is the data and its origin:

![bug](https://user-images.githubusercontent.com/115270/38801655-be313c70-416a-11e8-90e0-be30bd4d8ad8.jpg)

**Comment by nicolaisi** [comment]
I'll look into this.

**Comment by matze** [comment]
@raghavaro also merge this one.
