### ISSUE TITLE
Occasional glitch when loading data

### ISSUE THREAD

**Issue by matze** [kit-ipe/WAVE-Client-Renderer#35]
Once in a while data is not load correctly and a few slices contain garbage data with expected results, as seen on the left side:

![glitch](https://user-images.githubusercontent.com/115270/38810139-20f018d4-4186-11e8-8062-e9bdb96cec23.jpg)

Hitting F5 resolves it but it's still not a nice experience. Nevertheless #34 is more important at the moment, so this is just for the record.

**Comment by nicolaisi** [comment]
Thanks for the report 👍 Definitely need to fix this.

**Comment by nicolaisi** [comment]
I think this 9702ad5b7073026b8c196398d5dad3a3a43b696f should resolve this issue. Try it out and let me know if this still persists.
