### ISSUE TITLE
Speedup Ray tracing algorithm

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/WAVE-Client-Renderer#4]
So far, we're just stepping through every pixels on the view plane and trace the rays. Well, this is fine for showcase, but should be sped up somehow.
1. Probable way is to use kd-trees to identify the region of intersections and traverse through this tree.

**Comment by sogimu** [comment]
Useful survey article.
"A Survey of GPU-Based Large-Scale Volume Visualization"
http://vcg.seas.harvard.edu/files/pfister/files/paper107_camera_ready.pdf
